version: "3"

networks:
  react-app-network:
    external: true

services:
  cpqd-react-app:
    image: react-app
    build: 
      context: "."
      dockerfile: "docker/Dockerfile.prod"
    container_name: react-app
    hostname: react-app
    ports:
      - "5000:5000"
    volumes:
      - "./resources/default.conf.template:/etc/nginx/conf.d/default.conf.template"
      - "./resources/default.conf.template:/etc/nginx/conf.d/default.conf"
      - "./resources/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - react-app-network
    env_file:
      - .env
    restart: always
